### ISSUE TITLE
BioTec-L support

### ISSUE THREAD

**Issue by serviser** [9a4gl/lovelace-centrometal-boiler-card#1]
As the owner of a BioTec-L boiler, I wonder if I can help to get this type of boiler supported?

**Comment by 9a4gl** [comment]
Card supports only peltec for now, cmpelet will be hard and I will support only basic items probably, but later, BoTec-L I have to see what I can do.

But, first try https://github.com/9a4gl/hass-centrometal-boiler integration, it is still not available in HACS by default so you will have to add repository if you use HACS (it shall be be availabe soon there). 

We need to see if integration works and what has to be fixed to get proper entities from BioTec-L. Feel free to contact me on whatsapp +385 91 185 70 50. 

Tihomir

**Comment by 9a4gl** [comment]
Support for BioTec (-L) has been added
