### ISSUE TITLE
Cm Pelet set - touch support

### ISSUE THREAD

**Issue by najdanovicivan** [9a4gl/lovelace-centrometal-boiler-card#2]
I've tried using the lovelace card with the Cm Pelet Set touch and it's not working. I noticed some differences in sensor naming 

fist all sensor names are prefixed with `cm_pelet_set` not `cm_pelet` aslo sensosrs b_cp and b_smd does not exist.

Here are all all the available entities
<img width="1599" alt="Screenshot 2022-01-27 at 21 32 33" src="https://user-images.githubusercontent.com/6421209/151439258-4e889c2d-8651-4f03-bf94-c8ade21ad482.png">
<img width="1743" alt="Screenshot 2022-01-27 at 21 32 49" src="https://user-images.githubusercontent.com/6421209/151439268-809243ed-d675-4525-abc4-f17a3e91ac21.png">
<img width="1851" alt="Screenshot 2022-01-27 at 21 33 33" src="https://user-images.githubusercontent.com/6421209/151439273-91f18fda-eeba-464e-875a-537438213b7a.png">
<img width="1620" alt="Screenshot 2022-01-27 at 21 33 48" src="https://user-images.githubusercontent.com/6421209/151439277-bfc0a817-5af9-4f1d-a2ee-577f913a25a2.png">
<img width="1614" alt="Screenshot 2022-01-27 at 21 33 57" src="https://user-images.githubusercontent.com/6421209/151439283-eec4b283-7829-4fa8-8857-dc98ea46433b.png">

**Comment by 9a4gl** [comment]
cm_pelet_set prefix is fine, but missing parameters is problem. Currently the integration has been tested only with one cmpelet set installation which is probably different, and honestly cmpelet-set was quite difficult for me to understand as centrometal web app is most complicated with too many possibilities. Let's continue in private to see how to proceed with this, but I think I will need to debug integration with your instalation.
