### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by RobertBarbo** [9a4gl/lovelace-centrometal-boiler-card#4]
hello,
first at all i have to thank you for making this project. I really like it.
But i have a problem, am using biotecl and my card is missing radiator picture for 1.st circuit with room temp.

What am i doing wrong?

Pozz

**Comment by 9a4gl** [comment]
Hi, some things have been blindely implemented as I do not have access to all boilers. Some people helped be and provided me access to their boilers so I can test and compare result on centrometal portal and my card.
Also centrometal never replied to my mails to get any support from them.
If you want you can contact me on whatsapp +385 91 1857050 and give me credential so I can access centrometal portal and then I can implement missing features for your setup.

**Comment by 9a4gl** [comment]
Mo reply from reporter
