### ISSUE TITLE
TypeError: Cannot create property 'scale_factor'

### ISSUE THREAD

**Issue by CycloneHR** [9a4gl/lovelace-centrometal-boiler-card#5]
Hello,
I started using HA relatively recently and was delighted to find support for Peltec.
I was even more excited when I found this card :)

But unfortunately that's where the problems start :(
I added a card via HACS, I see it in resources, I added a new custom card to dashboard:
_type: custom: centrometal-boiler-card
device_type: peltec_

but I get an error:
_Error: Parameter "configuration" neither detected nor configured._

Details from the log:
_2023-11-17 22:01:12.263 ERROR (MainThread) [frontend.js.latest.202309110] Uncaught error from Chrome 119.0.0.0 on Windows 10
TypeError: Cannot create property 'scale_factor' on string 'Parameter "configuration" nor detected nor configured.'
/hacsfiles/lovelace-centrometal-boiler-card/centrometal-boiler-card.js:21:37
ResizeObserver.<anonymous> (/hacsfiles/lovelace-centrometal-boiler-card/centrometal-boiler-card.js:19:15)_

Regars

**Comment by 9a4gl** [comment]
Few questions first. Have you added intgration and using integration have you added the device? Does it show and you see all the the entities of device to have some meaningfull values?
Second, what boiler do you have?

**Comment by CycloneHR** [comment]
Thank you for a quick response.
Yes, of course, first I added HACS and then I added Centrometal integration and device with all its entity's.
I have a Peltec lambda boiler and in HA I can see all correct values from all sensors.
I created a custom entity card on my dashboard like this one:

![Screenshot_20231118_104158_Home Assistant](https://github.com/9a4gl/lovelace-centrometal-boiler-card/assets/145850799/3907093c-4b51-4e66-b6f7-bdb66b385597)

Is there a possibility that the error is caused by the fact that I run HA directly on the Win10 machine: 
Home Assistant Windows Portable (HassWP)?

**Comment by 9a4gl** [comment]
Huh, bio sam malo u gužvi. Iskreno nitko nije imao ovaj problem, probao instalirati hassio u virtualku, tako ja radim, ne znam specifičnosti HassWP, čak nisam znao da je to uopće moguće. 
Jedino što mogu je da mi daš username/password pa probam, ali s obzirom da imaš istu peć, hm, nemam ideju. Ako želiš da ja probam kontaktiraj me whatsapp +385 91 185 7050 pa probam vidjeti gdje je problem.

**Comment by 9a4gl** [comment]
It does not work in HassWP ... user installed hassio and now it works fine
