### ISSUE TITLE
Error parameter "boiler_state" nor detected nor configured

### ISSUE THREAD

**Issue by AndroFlo** [9a4gl/lovelace-centrometal-boiler-card#6]
Hi,

Firstly thank you for your work.

hen i add a card with type: custom:centrometal-boiler-card
My boiler is a biotec plus 

I have the error 

![Capture d’écran 2023-12-07 à 15 35 00](https://github.com/9a4gl/lovelace-centrometal-boiler-card/assets/5589240/b681ece5-b104-4270-ae8c-d2053ac186a0)

Thank you

**Comment by 9a4gl** [comment]
Do you have centrometal boiler device in devices? And is there an entity like sensor.*_boiler_state ?

**Comment by AndroFlo** [comment]
Yes,i have **sensor.gmx_easy_boiler_state**

**Comment by 9a4gl** [comment]
That means you entered prefix when adding integration, either define prefix for card (prefix are introduced to support multiple boilers in same HA instance), so you shall have something like:
type: custom:centrometal-boiler-card
prefix: gmx_easy
Od you can remove integration and add again without prefix. 
Let me know if this helps.

**Comment by AndroFlo** [comment]
No, i have only type: custom:centrometal-boiler-card , in the card configuration

**Comment by 9a4gl** [comment]
Wait, you do not have biotec plus, but gmx easy, is this your boiler https://www.chaudieres-morvan.com/chaudiere/gmx-easy/ ?
If yes, then this boiler is not supported and I would need to add support for it, looks it is centrometal boiler under some other brand.
The easiest would be if you contact me on whatsapp +385 91 185 7050 and give me credentials so I can connect using your account and add the boiler.

**Comment by 9a4gl** [comment]
You can also try following (may or may not work, not sure):
- type: custom:centrometal-boiler-card
  device_type: biopl
  prefix: gmx_easy

**Comment by AndroFlo** [comment]
Not working with prefix, i sended you my credentials with whatsapp

**Comment by 9a4gl** [comment]
Added support for Morvan GMX EASY boilers
